const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Flash,
		C3.Plugins.Text,
		C3.Plugins.Arr,
		C3.Plugins.Mouse,
		C3.Plugins.Button,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.time,
		C3.Plugins.Arr.Acts.SetInstanceVar,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Cnds.CompareCurrent,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{PrevTurnTakerUID: 0},
	{Names: 0},
	{Turn: 0},
	{Health: 0},
	{Flash: 0},
	{William: 0},
	{MaleZombie: 0},
	{Player1health: 0},
	{TurnOrder: 0},
	{Anton: 0},
	{Johan: 0},
	{Sprite4: 0},
	{Alesya: 0},
	{Player2health: 0},
	{Player3health: 0},
	{Playerhealth4: 0},
	{Enemy1health: 0},
	{Mouse: 0},
	{TFValue: 0},
	{AttackButton: 0},
	{Sprite2: 0},
	{Button: 0},
	{Audio: 0},
	{Sprite: 0},
	{Text: 0},
	{TurnTeller: 0},
	{Sprite3: 0},
	{Text2: 0},
	{Aattackbutton: 0},
	{Sprite5: 0},
	{Text3: 0},
	{TurnTakers: 0},
	{WhoseTurn: 0},
	{IsTurnEnding: 0},
	{AttackChoice: 0},
	{TurnTime: 0},
	{IsPlayerTurn: 0}
];

self.InstanceType = {
	William: class extends self.ISpriteInstance {},
	MaleZombie: class extends self.ISpriteInstance {},
	Player1health: class extends self.ITextInstance {},
	TurnOrder: class extends self.IArrayInstance {},
	Anton: class extends self.ISpriteInstance {},
	Johan: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Alesya: class extends self.ISpriteInstance {},
	Player2health: class extends self.ITextInstance {},
	Player3health: class extends self.ITextInstance {},
	Playerhealth4: class extends self.ITextInstance {},
	Enemy1health: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	AttackButton: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	Audio: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	TurnTeller: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Aattackbutton: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	TurnTakers: class extends self.ISpriteInstance {}
}