const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Bullet,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.TiledBg,
		C3.Plugins.progressbar,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.progressbar.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Behaviors.EightDir.Acts.SetSpeed,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.OnLayoutStart
	];
};
self.C3_JsPropNameTable = [
	{Health: 0},
	{"8Direction": 0},
	{ScrollTo: 0},
	{BoundToLayout: 0},
	{player: 0},
	{Bullet: 0},
	{goblin: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{TiledBackground: 0},
	{TiledBackground3: 0},
	{fireball: 0},
	{ProgressBar: 0},
	{Fade: 0},
	{Poof: 0},
	{MUC: 0},
	{Text: 0},
	{Audio: 0}
];

self.InstanceType = {
	player: class extends self.ISpriteInstance {},
	goblin: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	fireball: class extends self.ISpriteInstance {},
	Health: class extends self.ISpriteInstance {},
	ProgressBar: class extends self.IProgressBarInstance {},
	Poof: class extends self.ISpriteInstance {},
	MUC: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {}
}